[package]
name = "hacl-star"
version = "0.0.7"
authors = ["quininer <quininer@live.com>"]
description = "HACL*, a formally verified cryptographic library for Rust (binding to hacl-c)."
keywords = [ "hacl-star", "cryptographic" ]
categories = [ "cryptography" ]
repository = "https://github.com/quininer/rust-hacl-star"
documentation = "https://docs.rs/hacl-star/"
license = "MIT"

[workspace]

[features]
bindgen = [ "hacl-star-sys/bindgen" ]

[badges]
travis-ci = { repository = "quininer/rust-hacl-star" }
appveyor = { repository = "quininer/rust-hacl-star" }

[dependencies]
rand_core = { version = "0.1", default-features = false }
libc = { version = "0.2", default-features = false }
hacl-star-sys = { version = "0.0.5", path = "hacl-star-sys" }
